### ISSUE TITLE
pam_systemd shouldn't be optional in system-auth

### ISSUE THREAD

**Issue by pbrezina** [pbrezina/authselect#118]
Bugzilla:
https://bugzilla.redhat.com/show_bug.cgi?id=1643928

**Comment by abbra** [comment]
This broke FreeIPA when default HBAC rule allow_all is disabled (something everyone needs to do in production). See https://bugzilla.redhat.com/show_bug.cgi?id=1664974 for details on RHEL 8. What's worse, it affects any deployment where a new RHEL 8 IPA client would be introduced, even if the rest is run on other versions. Nobody will be able to login to the system unless systemd-user HBAC service is created and allowed in HBAC rules.

This is a huge problem.
