### ISSUE TITLE
Use setfscreatecon to create content in /etc/authselect with a proper context

### ISSUE THREAD

**Issue by doverride** [pbrezina/authselect#128]

**Comment by doverride** [comment]
https://www.systutorials.com/docs/linux/man/3-setfscreatecon/

Because the alternative would be to run restorecon -RvF /etc/authselect (or equivalent) to ensure proper labeling and that would be racy.

files like /etc/authselect/nsswitch.conf need to be labeled properly, and you create them with a random suffix so there is no other way to ensure proper labels.

**Comment by doverride** [comment]
I seem to recall that at some point you actually did this properly but that is no longer the case, and i cannot find any trace of any changes in this regard in your git log

**Comment by doverride** [comment]
it was probably authconfig-compat that did this properly...

**Comment by pbrezina** [comment]
Thanks, I will look into it.

**Comment by pbrezina** [comment]
PR: https://github.com/pbrezina/authselect/pull/131
