### ISSUE TITLE
Use attribute cleanup instead of cleaning up manualy

### ISSUE THREAD

**Issue by jhrozek** [pbrezina/authselect#13]
because authselect is Linux-specific, we can make use of attribute cleanup instead of cleaning up manually like it's the 80s.

This could be done e.g. for tmpfiles, memory etc

**Comment by pbrezina** [comment]
Authselect is Linux and Fedora/RHEL specific, but I still wonder -- how is this portable across various compilers?

**Comment by jhrozek** [comment]
It is not in general, but it is implemented in GCC and CLANG. But feel free to close the ticket if you disagree, it's just something I would probably use if I started a new C project now.

**Comment by pbrezina** [comment]
I'm closing this ticket for now as there are no plans to use gcc attributes for clean up.
