### ISSUE TITLE
please produce a new release including authselect-1.0.3 translations

### ISSUE THREAD

**Issue by Jibec** [pbrezina/authselect#143]
hello, I have been working on translating the whole authselect content in French and noticed a few changes on authselect core.

So I fixed the last sentences, and decided to come here to see what's happening.

What I understand of what happened:

- translation were pull here, the pot file was updated and pushed to zanata
- a new release was done

The issue: the last strings changed are now untranslated in the release for languages nl, fr, sv, uk, ja, es.
A side effect is that I did not had time to finish french translations, docs are probably half translated in the last release... Quite frustrating.

As your project is identified in our group "main", we understand it follows Fedora's release cycle:

* the software string freeze was on 2019-02-05
* the Software Translation Deadline is 2019-03-05

See: https://fedoraproject.org/wiki/Releases/30/Schedule

So, this is no big deal and easy to fix: can you please produce a new authselect release after string freeze?

To prevent this in the future, please just send an email to trans@lists.fedoraproject.org informing us of your particular deadlines.

Thanks a lot of your help and understanding

**Comment by pbrezina** [comment]
Hi, thank you for this translation. This is so far just an upstream release and was not yet pushed to any Fedora version (although I plan to do it). I will include these translations prior pushing it to Fedora. There will be definitely a new release for F30 after string freeze.

**Comment by pbrezina** [comment]
I've updated the 1.0.3 release with recent translations.
