### ISSUE TITLE
Allow setting default minimal UID

### ISSUE THREAD

**Issue by mikhailnov** [pbrezina/authselect#159]
I want to adapt authselect for ROSA distribution, may be I will send some patches implementing missing config features, but the problem is that the default minimal UID/GID is 500, not 1000. It is not a problem to use `sed` when building the package, but it would be nice to make it configurable.

**Comment by pbrezina** [comment]
Hi. This is a problematic issue. On one hand I am very glad that authselect might me adopted by other distribution than Fedora/RHEL. On the other hand, what you ask goes against authselect philosophy - i.e. provide testable configuration that is known to work and will not lock the system. If we allow to use user provided values, it may break the system if unexpected value was given.

That being said, I do not strongly oppose this, I thought about it several times myself. I'm just saying that it would have to be thoroughly designed before we start to implement it. If you have time to work on it, please, feel free to come with a design page and we can talk about it.

However, this is the first request for such feature. So perhaps it is not needed on user level but only on distribution level. For this reason we have implemented so called ["vendor" profiles](https://github.com/pbrezina/authselect/wiki/Profiles:-Types#vendor-profiles). This will allow you to ship your own version of upstream profiles where you can do any modifications you need.

If you want to reduce maintainer cost and always pickup latest upstream profile, perhaps you can use something like `authselect create-profile sssd --vendor --base-on sssd ... && sed (your modification)` in your rpm.

**Comment by mikhailnov** [comment]
Well, for now `grep -Irl " 1000 " . | xargs sed -i "s/ 1000 / 500 /g"` from the source of authselect (https://abf.io/import/authselect/blob/rosa2016.1/authselect.spec#lc-230) works well to change UID/GID both in profiles and documentation.

I don't want to make any vendor profiles because default ones have been well tested and suite ROSA distribution very well.

So, everything is OK at the moment.

**Comment by pbrezina** [comment]
Thank you. I'm closing this ticket for now. Feel free to reopen it if any further discussion is needed.

**Comment by pbrezina** [comment]
There is a new module in pam that can perhaps help with this:
https://github.com/linux-pam/linux-pam/commit/926d7935edf35385e6c28bb97666aee443b71e46

It is included in authselect-1-2:
https://github.com/authselect/authselect/commit/4cfb20423ca9a3e9b2b3de627b751e61fb0cf560
