### ISSUE TITLE
Do you know/can explain why this project is used in Fedora only?

### ISSUE THREAD

**Issue by q2dg** [pbrezina/authselect#180]
See https://repology.org/project/authselect/versions
Is it related to something structurally specific to Fedora? 
Thanks!

**Comment by pbrezina** [comment]
No, it can be used in any distribution, not just Fedora. However besides Fedora (and RHEL) only Rosa distribution have included it so far.

**Comment by q2dg** [comment]
Ok, thanks.

Maybe someone from Fedora could do something about "evangelize" this tool in other distros in order to package it, because it's a pity it is so specific.

I'll keep this issue open to keep track about this situation but feel free to close it if you consider it.

**Comment by pbrezina** [comment]
What distro do you use? Maybe you can try to push it there?

**Comment by q2dg** [comment]
Ubuntu. I'm just a base user...I don't think someone could keep me in mind.
Anyway, I've put this request here...: https://askubuntu.com/questions/1164750/could-someone-package-authselect-for-ubuntu-thanks
If you don't mind, I'll close the issue because it seems there's nothing to do here. 
Thanks!!
