### ISSUE TITLE
please migrate to the new Fedora translation platform

### ISSUE THREAD

**Issue by Jibec** [pbrezina/authselect#186]
Hello, the Fedora project migrates its translation platform to Weblate [1].

This tool directly interact with your git repository, and requires us to know:
* [mandatory] which branch is your development branch?
* [mandatory] have you merged latest translation from Zanata and locked the project?
* [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
* [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)
* [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)
* [optional] do you need us to activate any specific checks? (this is a setting per component [3])
* [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Please note:
* For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.
* In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
* You can change your mind over time, just reach trans@lists.fedoraproject.org

[1] https://communityblog.fedoraproject.org/fedora-localization-platform-migrates-to-weblate/ 
[2] https://docs.weblate.org/en/latest/admin/continuous.html#avoiding-merge-conflicts
[3] https://docs.weblate.org/en/latest/user/checks.html#translation-checks

**Comment by pbrezina** [comment]
I would like to move authselect to standalone organization on github so it is not hosted under my user account so Weblate needs to be probably configured after that.

**Comment by Jibec** [comment]
If you are unsure you'll do this on the coming days, it would help me to first do the migration, and then change the git repo. The more migrates at the same time, the easier it is for our community.

In fact, you'll be admin of your project in weblate, i can document the steps to change weblate configuration when you'll do the change.

Would it be fine for you?

**Comment by pbrezina** [comment]
Sure, see answers below.

>     * [mandatory] which branch is your development branch?
master: latest development
1.0.x: bugfixes to 1.0 version

>     * [mandatory] have you merged latest translation from Zanata and locked the project?

Yes. FYI I set the project to be read only. Please tell me if there is anything else I need to do.

>     * [info] Weblate will handle updates when pot file changes, don't edit po files for this [2]
>     * [optional] what is the license of translation? (please use a code from https://spdx.org/licenses/)

Is it already licenced in Zanata? The code is GPL3.

>     * [optional] do you have any announcement/warning you would like to display to the translators? (it will be displayed in Weblate)

No.

>     * [optional] do you need us to activate any specific checks? (this is a setting per component [3])

I often have to fix trailing new lines in Zanata. Can this be done automatically?

>     * [optional] do you need us to automatically detect new translation files? (typical usecase: website translation with one translation file per page)

Would be nice.

> 
> 
> Please note:
> 
>     * For github hosted projects, Weblate open pull request. For other project, you'll have to add a key to allow commits.

I only update translations before release. Is it possible to avoid opening pull request for each change?

>     * In Weblate's vocable, one project is a group of component. Each component is a translation file. You can have many projects or many components or both.
> 
>     * You can change your mind over time, just reach [trans@lists.fedoraproject.org](mailto:trans@lists.fedoraproject.org)

My current use case is to run `zanata-cli pull` or `zanata-cli push` with some [hooks](https://github.com/pbrezina/authselect/blob/master/scripts/zanata-hooks.sh) that takes care of converting manual pages that are in asciidoc to pot file. Will this be possible?

**Comment by Jibec** [comment]
Project is configured: https://translate.stg.fedoraproject.org/projects/authselect/
I can't add you as admin as I don't see you in the list of users, please connect.

do you want us to also translate the 1.0 branch and/or other branches?

A pull request was opened by Weblate, keep it open until you release.
Weblate will update every po files each time you update the pot, don't manually touch to po files two.

I don't know why you have so many new lines in your file, let's wait a little bit and see if we can improve the situation.

**Comment by pbrezina** [comment]
> Project is configured: https://translate.stg.fedoraproject.org/projects/authselect/
> I can't add you as admin as I don't see you in the list of users, please connect.

I should be there now: pbrezina.

> do you want us to also translate the 1.0 branch and/or other branches?

No, just `master` and `1.0.x`.

> A pull request was opened by Weblate, keep it open until you release.
> Weblate will update every po files each time you update the pot, don't manually touch to po files two.

There are now two pull requests opened:
https://github.com/pbrezina/authselect/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen++weblate

Why? Is it a misconfiguration?

> I don't know why you have so many new lines in your file, let's wait a little bit and see if we can improve the situation.

The new lines were translators errors, i.e. new lines at the end of translation did not match new lines in the original message. Zanata mark those as invalid translation but I had to fix it manually. Is it possible to setup Weblate to autocorrect these translations errors?

**Comment by pbrezina** [comment]
Ping. Are there any news? I'm still not the project maintainer.

**Comment by Jibec** [comment]
migration is done: https://translate.fedoraproject.org/projects/authselect

both branches were configured
weblate will handle po updates each time the pot file is changed
weblate will squash commits per contributors

weblate will help translators to propagate translations in both of your branches, you don't have anything to do, you should not merge po files.
