### ISSUE TITLE
add files only profile for system with memory constrains

### ISSUE THREAD

**Issue by robo2bobo** [pbrezina/authselect#187]
Hello,

I've been using authselect under Fedora and CentOS and I always have a problem when I want to disable sssd or nis, essentially I have to do it manually because there is no way to tell authselect to unselect the nis/sssd/winbind profiles.

Maybe what I'm asking is a "files" profile that will remove all nis/sssd/winbind related parameters and go back to plain /etc files authentication?

This is especially important, when I remove all sssd packages, the leftover sssd entries confuse systemd, for example:
```
systemd[18718]: PAM unable to dlopen(/usr/lib64/security/pam_sss.so): /usr/lib64/security/pam_sss.so: cannot open shared object file: No such file or directory
systemd[18718]: PAM adding faulty module: /usr/lib64/security/pam_sss.so
```

I'm requesting a new feature that either deselects all profiles:
```
authselect select none
```
or selects a "files" profile:
```
authselect select files
```

Thank you.

**Comment by pbrezina** [comment]
Why do you want to remove sssd?

**Comment by robo2bobo** [comment]
Well, for many reasons:

- my servers don't use it
- my VM containers don't use it
- unload the systemd sssd module/service that is not used
- free up memory
- for security reasons, if its not there, it can't be hacked/compromised ;)

overall I see that RedHat has decided to load/run sssd and smart cards in Fedora/RHEL/CentOS by default, which is something understandable considering they cater to their own clients. For me, all these should not be installed by default, I prefer to start with a minimal system and build on top of that.

at least allow us to cleanly remove the profiles.

thank you.

**Comment by dpal** [comment]
Hello,

You are right about the defaults that we assume. You are saying that our assumptions do not apply in your case. Can you please help us understand what is special about your environment and why SSSD with all its capabilities is not appealing? Depending upon how widespread is your case our approach to addressing the problem you raise might be different.

Thank you,
Dmitri

**Comment by robo2bobo** [comment]
Hello there,

I wouldn't say my environment is special, just slightly different. I handle 100+ servers that handle specific workload, like email servers, or desktops for office/business use.

The servers are usually cloud VMs with little memory (2GB or less). I use minimal install of RHEL or CentOS and an ansible playbook to customize them. Due to memory constraints I need to remove anything not related to the server's work and in 100% of cases I need to remove sssd, networkmanager, avahi, alsa, fprintd, mcelog, teamd, lvm, plymouth, kexec, systat and many many other packages.

In RHEL 7, the default authconfig was "nis", so when I removed sssd, there where no problems.

In RHEL 8, the default authselect is "sssd", which can be removed by just uninstalling all the packages, but something is left over that causes systemd to report errors. I couldn't find an authselect command to switch to just "files" authentication, essentially I had to do it on my own by modifying the files under /etc/pam.d/ and /etc/authselect/nsswitch.conf to remove all traces of sssd.

Thus my bug report. It would be nice to either have an "authselect select none" to unselect the selected profile, or maybe a system default profile for "files" that we may select as "authselect select files", to disable nis/sssd.

Thank you.

**Comment by pbrezina** [comment]
Thank you for the information. We have denied plain files profile without SSSD multiple times in the past but since this issue keeps reoccurring and with your thorough explanation we have re-evaluated our strategy. We will provide such profile in next upstream release (for Fedora 32) and bring it to RHEL as well.

**Comment by robo2bobo** [comment]
My apologies for asking for more development and thank you for accepting my feature request!

**Comment by pbrezina** [comment]
@robo2bobo Would you be willing to test it? I can provide you a test package if you tell me what RHEL version do you use.

**Comment by robo2bobo** [comment]
I can definitely test packages on CentOS 7 and CentOS 8. I can also perform extra testing with ansible.

**Comment by robo2bobo** [comment]
I did a quick test of the new 'minimal' profile, overall it seems to work ok.

I am not sure about `profiles/minimal/dconf-locks` since all my servers are headless.

I do have several differences with the CentOS 8 profile, for example the account section is very different:

```
account     required                                     pam_unix.so broken_shadow
account     sufficient                                   pam_localuser.so
account     sufficient                                   pam_succeed_if.so uid < 1000 quiet
account     required                                     pam_permit.so
```

I'll run some more tests.

**Comment by pbrezina** [comment]
> I did a quick test of the new 'minimal' profile, overall it seems to work ok.

Thank you.

> I am not sure about `profiles/minimal/dconf-locks` since all my servers are headless.

I'll check if it is needed for Gnome. But I guess the default value will be disabled for those options so we can just omit it to make it smaller.

> I do have several differences with the CentOS 8 profile, for example the account section is very different:
> 
> ```
> account     required                                     pam_unix.so broken_shadow
> account     sufficient                                   pam_localuser.so
> account     sufficient                                   pam_succeed_if.so uid < 1000 quiet
> account     required                                     pam_permit.so
> ```
> 
> I'll run some more tests.

`pam_localuser` and `pam_succeed_if` are not necessary here. The are used to skip the following module if it is a localuser or system account. So it is used to skip e.g. `pam_sss`. `pam_permit` is not needed since we already have either success or failure from `pam_unix`.

**Comment by pbrezina** [comment]
I removed dconf settings since it uses default values anyway.

**Comment by pbrezina** [comment]
* `master`
  * 2c4036588113e29eceb0da52921938a069dec1e1 - profiles: add minimal profile for systems with disk and memory constraints
