### ISSUE TITLE
authselect-1.1-6.fc32 seems unable to restore the default configuration

### ISSUE THREAD

**Issue by fcami** [pbrezina/authselect#197]
I have two backups:
```
# authselect backup-list
2020-02-07-22-33-43.M8fOg6 (created at Fri 07 Feb 2020 11:33:43 PM CET)
2020-02-07-22-38-28.Uukas2 (created at Fri 07 Feb 2020 11:38:28 PM CET)
```
the first one is a backup of the default configuration done in rawhide (authselect-1.1-6.fc32.x86_64).
Trying to restore it fails:
```
[error] Unable to restore [2020-02-07-22-33-43.M8fOg6] [2]: No such file or directory
Unable to restore backup [2020-02-07-22-33-43.M8fOg6] [2]: No such file or directory
```
Using strace, we see it successively choke on:
```
openat(AT_FDCWD, "/var/lib/authselect/backups/2020-02-07-22-33-43.M8fOg6/dconf-db", O_RDONLY) = -1 ENOENT (No such file or directory)
```
and:
```
openat(AT_FDCWD, "/var/lib/authselect/backups/2020-02-07-22-33-43.M8fOg6/dconf-locks", O_RDONLY) = -1 ENOENT (No such file or directory)
```
Simply creating empty files:
```
# touch /var/lib/authselect/backups/2020-02-07-22-33-43.M8fOg6/dconf-db
# touch /var/lib/authselect/backups/2020-02-07-22-33-43.M8fOg6/dconf-locks
```
makes it work:
```
# authselect backup-restore 2020-02-07-22-33-43.M8fOg6
```
and the backuped nsswitch is now identical to the original:
```
config]# md5sum nsswitch.conf /etc/nsswitch.conf
5cc1a8341dbebe35bab636912a0e4b47  nsswitch.conf
5cc1a8341dbebe35bab636912a0e4b47  /etc/nsswitch.conf
```
from the [FreeIPA bug report](https://pagure.io/freeipa/issue/8189)

If you need any more information please let me know.

**Comment by pbrezina** [comment]
Thank you. PR: https://github.com/pbrezina/authselect/pull/202

**Comment by pbrezina** [comment]
Please, find test builds for f32 [1] or rawhide [2]

[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=41467298
[2] https://koji.fedoraproject.org/koji/taskinfo?taskID=41467290

**Comment by pbrezina** [comment]
* `master`
  * c8fa7098fc46cf583ccd0ad37792dc9f6509f48e - backup-list: return empty array if directory does not exist
  * 59149a3487e0487c8d4138d000de9ed9afeef1a8 - backup: do not unlink dangerous missing files
  * 8a3ea7d955392c76e4f62e1efb23dcfd930c3f6e - backup: remove authselect.conf when restoring non-authselect configuration
  * 5165e5e62672f61498d3c3fbc77897171d1f9273 - backup: remove non-existing files when restoring non-authselect configuration

**Comment by fcami** [comment]
Hi @pbrezina the build at https://koji.fedoraproject.org/koji/taskinfo?taskID=41467298 fixes the issue on a non-FreeIPA rawhide reproducer at least. Thank you very much!
