### ISSUE TITLE
ship a bash/zsh completion script

### ISSUE THREAD

**Issue by jhrozek** [pbrezina/authselect#31]
My  hands hurt from typing.

**Comment by pbrezina** [comment]
This is a good idea. Do you have any experience with this?

**Comment by jhrozek** [comment]
From a long time ago..but this is not a very urgent ticket

**Comment by pbrezina** [comment]
* `master`
  * b9d77ad6225ce8ab1fa3c0833d968d6da9409f0d - bash: Add bash completion script

**Comment by e9x** [comment]
> My hands hurt from typing.
real shit g
