### ISSUE TITLE
sssd smartcard-auth profile syntax error?

### ISSUE THREAD

**Issue by ryancurrah** [pbrezina/authselect#35]
I noticed a potential syntax error in the sssd smartcard-auth profile where there is an erroneous additional `?` on [line 1](https://github.com/pbrezina/authselect/blob/master/profiles/sssd/smartcard-auth#L1).

**Comment by pbrezina** [comment]
Hi, thank you for testing.

This syntax is correct, see: [authselect-profiles](https://github.com/pbrezina/authselect/blob/master/src/man/authselect-profiles.5.txt.in.in#L71). Authselect will stop generating the file unless `with-smartcard` feature is enabled.

I understand that it is not very clear from the syntax. We wanted to keep the parser as simple as possible.
