### ISSUE TITLE
dconf dependency

### ISSUE THREAD

**Issue by akokshar** [pbrezina/authselect#43]
it seems that the package build from this repo is missing dependency on dconf. After 'dnf install dconf' it kind of work, but before it was throwing and error: 
$ sudo authselect select sssd       
$ sh: /usr/bin/dconf: No such file or directory

This is breaking the scripts calling to authselect

**Comment by pbrezina** [comment]
Thanks, fixed in 4b0f17ec0688237c9d59a66ff85a5189e83d7319
