### ISSUE TITLE
Maybe wrong error data in file.c:file_check_type

### ISSUE THREAD

**Issue by lonemadmax** [pbrezina/authselect#44]
https://github.com/pbrezina/authselect/blob/8ee9fb9a9362bfa48bbb88cd1dda4cd8f3b3ed29/src/lib/util/file.c#L58 doesn't look right, same data for wrong and expected?. Maybe
`                  name, (statbuf->st_mode & S_IFMT), exp_type);`
?
(Not that I have even compiled the code, I was just translating strings)

**Comment by pbrezina** [comment]
Yes, you are right. It is fixed in 6e390e8273d65c74234c22ceb6460373f5506bfe. Thank you.
