### ISSUE TITLE
sssd password-auth and system-auth profile behavior not as expected

### ISSUE THREAD

**Issue by ryancurrah** [pbrezina/authselect#45]
We are testing the SSSD auth profiles in this repo due to RedHat mentioning in the [7.4 release notes](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.4_release_notes/chap-red_hat_enterprise_linux-7.4_release_notes-deprecated_functionality) that authselect will replace authconfig. We found that the configuration of the SSSD profiles `password-auth` and `system-auth` on lines 4 to 9 did not work as expected.

https://github.com/pbrezina/authselect/blob/d034782d2df9d9b64bb03096229f64ddae0f2166/profiles/sssd/password-auth#L4-L9

and...

https://github.com/pbrezina/authselect/blob/d034782d2df9d9b64bb03096229f64ddae0f2166/profiles/sssd/system-auth#L4-L9

#### The behavior expected is that (starting from line 4)...

1. Users with a UID less than `1000` will not be allowed to login and will return a failed authentication result immediately to the calling application if the condition is met
2. Check if the user is a local user, if they are not a local user skip `pam_faillock` and `pam_unix` and try `pam_sss`

The reason we want to skip faillock for non-local users is to let SSSD's `auth_provider` to handle lockouts. The benefit of this is we can manage unlocking accounts centrally for example using Active Directory. 

The following example configuration would match our expected behavior...

```
auth        requisite                                    pam_succeed_if.so uid >= 1000 quiet_success
auth        [default=2 ignore=ignore success=ok]         pam_localuser.so
auth        requisite                                    pam_faillock.so preauth audit deny=3 unlock_time=900
auth        sufficient                                   pam_unix.so nullok try_first_pass
auth        sufficient                                   pam_sss.so forward_pass
auth        [default=1 ignore=ignore success=ok]         pam_localuser.so
auth        required                                     pam_faillock.so authfail deny=4 unlock_time=1200
```

Or it should look very similar to how this RedHat article recommends to configure PAM: [How to setup account lockout policy using pam_faillock when system is an LDAP client?
](https://access.redhat.com/solutions/880793)

#### The behavior we are experiencing using this projects SSSD `password-auth` and `system-auth` profile is that (starting from line 4)...

1. Users with a UID less than `1000` are able to login because the first `pam_succeed_if` does not fail the authentication immediately and the second `pam_succeed_if` will never run if `pam_unix` is successful due to the `sufficient` control field 
> sufficient - If the module succeeds the PAM framework returns success to the application immediately without trying any other modules. - https://linux.die.net/man/5/pam.conf
2. `pam_faillock` is ran for non-local users due to the check `pam_localuser` not skipping `pam_faillock`. This can be a confusing problem because users logging in with their Active Directory account would expect to get locked out from the directory service not locally on the server

Is there any document that details the rationale behind the selected PAM configuration that I may read so I can get an understanding of what it is trying to accomplish? Thanks!

**Comment by pbrezina** [comment]
Thank you for testing authselect. The generated pam stack is the same as what you would get with `authconfig --enablesssd --enablesssdauth --enablefaillock --updateall`.

I understand that it does not (and can't) cover all possible use cases. If you need different behavior, please create a custom profile (see `man authselect-profile`). Or you can open a pull request and we will consider supporting it in upstream.

**Comment by ryancurrah** [comment]
Thanks for your thoughts on this. Seems reasonable to create a custom profile.
