### ISSUE TITLE
What file can be modified since /etc/pam.d/password-auth should not ?

### ISSUE THREAD

**Issue by Paviluf** [pbrezina/authselect#52]
Hello,

I used to make these changes on Fedora to decrypt an encrypted folder on login with GDM but I noticed on Fedora 28 that the file "/etc/pam.d/password-auth" should not be edited manually. Here is the modification I made :

**/etc/pam.d/password-auth**
- At the top of "auth" section add
`auth        required      pam_mount.so`
- At the bottom of "session" section add
`session     optional      pam_mount.so`

**/etc/security/pam_mount.conf.xml**
`<volume user="yourusername" fstype="fuse" path="encfs#/path/.encrypted" mountpoint="/path/Decrypted" />`

Of course I made some research but didn't found anything. So what file can I edit to make it work ?
Thank you !

**Comment by Paviluf** [comment]
The problematic file is "/etc/pam.d/password-auth". It says that it has been auto generated by authselect and should not be modified.

**Comment by pbrezina** [comment]
Hi. If you want to touch configuration and keep using authselect, the way is to create a new profile. See man authselect-profiles [1]. You can also only extend existing profile by creating a new one and symlinking the files you do not want to change (we plan to provide some tooling for this but it is not yet in).

[1] https://github.com/pbrezina/authselect/blob/master/src/man/authselect-profiles.5.txt.in.in

**Comment by Paviluf** [comment]
Well, I modified /etc/pam.d/gdm-password that doesn't have the warning and that did the trick. Thanks !
