### ISSUE TITLE
Change of nsswitch.conf ordering breaks system users with override_homedir

### ISSUE THREAD

**Issue by opoplawski** [pbrezina/authselect#53]
I use override_homedir in sssd:

```
override_homedir = /export/home/%u
```
With the new "sss files" ordering, this breaks the home directory of system users:
```
# getent passwd gdm
gdm:x:42:42::/export/home/gdm:/sbin/nologin
```
instead of
```
gdm:x:42:42::/var/lib/gdm:/sbin/nologin
```
What was the reason for the change (commit 579932485e5dd46319d0f9f52e25f9b597917311)?  The commit message doesn't explain.

**Comment by opoplawski** [comment]
Getting varied results with sssd so not really sure what is all going on.  But I'm still very curious as to why this order was changed.  And so is jhodrien from sssd.

**Comment by pbrezina** [comment]
Hi, sssd has implemented a `files` provider that serves the local users and groups stored in `/etc/passwd` and `/etc/groups` files. This order has changed to `sss files` by default in F26 so the local users and groups can use sssd fast in-memory cache. This is not authselect, but sssd issue.

@jhrozek This is a known sssd issue?

**Comment by jhrozek** [comment]
Yeah, I saw the discussion in the scrollback and filed https://pagure.io/SSSD/sssd/issue/3758 to track this

**Comment by jhrozek** [comment]
btw the files provider can be disabled, see man sssd.conf, option enable_files_domain

**Comment by pbrezina** [comment]
Thank you. I'm closing this issue on authselect side.
