### ISSUE TITLE
Give packages way to modify nsswitch.conf

### ISSUE THREAD

**Issue by pbrezina** [pbrezina/authselect#77]
Authselect has the ability to perform nsswitch.conf modifications that are allowed by profiles. Existing nsswitch modules packages usually manually parse and modify nsswitch.conf during installation. Authselect should provide a way for these packages to perform the modification.

To make this feature really useful, we need to ensure that:
* when system is configured by authselect the changes are reflected in `/etc/authselect/user-nsswitch.conf`
* when system is **not** configured by authselect the changes are written in both `/etc/nsswitch.conf` (so they affect current configuration) and `/etc/authselect/user-nsswitch.conf` (so they affect possible future authselect configuration)

**Comment by keszybz** [comment]
Please review https://src.fedoraproject.org/rpms/systemd/pull-request/12.

**Comment by spstarr** [comment]
Why not just follow most packages using a <config-name.conf.d> structure?

/etc/nsswitch.conf.d/myoverrides.conf? 

Perhaps GNU libc should be managing this?

**Comment by pbrezina** [comment]
@keszybz I replied to the pull request.

@spstarr I though about this several times. This would work nicely if you have /etc/nsswitch.conf with default values and one file that overrides them (which would not bring anything), but adding more files would add conflicts and it would loose clarity and add problems with conflicts.

In my opinion, there is no good way to solve conflicts for nsswitch.conf as both usual "take-first, take-last" approaches does not really fit this use case (packages needs to extend the configuration) and correct merging is not doable with current syntax because you do not know what order the administrator wants to have. But I am open for discussion, if you have ideas on how to solve conflicts we can bring this to glibc.

As it turned out there are only two packages that writes to nsswitch.conf themselves (nss-mdns and systemd) so introducing authselect api for this is probably an overkill and we will find another way to do this, for now I asked their maintainers to make scriptlets compatible with authselect.

**Comment by pbrezina** [comment]
Per [discussion](https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/PNKKVG3K6WAU42CCPVIEV6LZY7PWUG4P/) on fedora-devel list, only package's scriptlets will be changed. I am closing this ticket for now.
