### ISSUE TITLE
nis: add sss module for passwd and group maps

### ISSUE THREAD

**Issue by pbrezina** [pbrezina/authselect#90]
SSSD is enabled by default to serve local users therefore even NIS profile should have it enabled for passwd and group.

Default `/etc/nsswitch.conf` in Fedora 27 looks like this:
```
$ cat /etc/nsswitch.conf | grep sss
passwd:      sss files systemd
shadow:     files sss
group:       sss files systemd
services:   files sss
netgroup:   nisplus sss
```

However, `nss_sss` does not implement `shadow`, therefore it should not be present. And `services` and `netgroup` does not have any meaning for local users domain so it should not be present either.

**Comment by imsedgar** [comment]
The changes in file profiles/nis/password-auth should belong to issue #88 , but is otherwise correct.

**Comment by pbrezina** [comment]
Fixed, thanks.

**Comment by pbrezina** [comment]
If users want to use sssd for nis objects they would rather use sssd profile. Using sssd only for local users and groups is possible but it may conflict with nscd that is often used to cache nis objects. Therefore it is not desirably to enable sssd for nis profile. I'm closing this ticket as rejected.
